# Generated by Django 4.2.2 on 2023-06-22 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='', max_length=250)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='entrepreneurs/profile_pictures/')),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(default=1)),
                ('episode_number', models.IntegerField()),
                ('pitch_number', models.IntegerField()),
                ('brand_name', models.CharField(max_length=255)),
                ('product', models.TextField()),
                ('present_sharks', models.JSONField()),
                ('pitcher_ask_amount', models.IntegerField()),
                ('pitcher_ask_equity', models.FloatField()),
                ('pitcher_ask_valuation', models.FloatField()),
                ('sector', models.CharField(max_length=255)),
                ('deal_or_not', models.BooleanField()),
                ('deal_valuation', models.FloatField()),
                ('entrepreneurs_founders', models.TextField()),
                ('deal', models.BooleanField()),
                ('deal_amount', models.IntegerField()),
                ('total_sharks_invested', models.IntegerField()),
                ('sharks_invested', models.JSONField(blank=True, null=True)),
                ('equity_per_shark', models.FloatField()),
                ('final_deal_debt', models.IntegerField()),
                ('final_deal_debt_interest', models.IntegerField()),
                ('social_media_links', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('profession', models.CharField(max_length=100)),
                ('award', models.TextField(blank=True, null=True)),
                ('career', models.TextField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, max_length=250, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='sharks/profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Pitch_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('1', 'Technology'), ('2', 'Food'), ('3', 'Fashion'), ('4', 'Health'), ('5', 'Home'), ('6', 'Skincare'), ('7', 'Fitness'), ('8', 'Education'), ('9', 'Entertainment'), ('11', 'Transportation'), ('13', 'Pet Care'), ('14', 'Agriculture'), ('15', 'Sports')], default='1', max_length=2)),
                ('cin', models.CharField(default='', max_length=50)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('all_time_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('last_year_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=25)),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.entrepreneur')),
            ],
        ),
    ]
