# Generated by Django 4.2.2 on 2023-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='deal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='deal_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='deal_or_not',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='deal_valuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='entrepreneurs_founders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='equity_per_shark',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='final_deal_debt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='final_deal_debt_interest',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitcher_ask_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitcher_ask_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='pitcher_ask_valuation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='present_sharks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='sharks_invested',
            field=models.JSONField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='total_sharks_invested',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
