# Generated by Django 4.2.2 on 2023-06-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pitch_brand_name_alter_pitch_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='deal_equity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
